### ISSUE TITLE
Openning the projet with a DBB full of contact is too long

### ISSUE THREAD

**Issue by maximeLeurent** [maximeLeurent/ContactGontran#10]
With 9000 contacts, the projet take some seconds to show the main window.
it's du to the filters in the table of contact.
By using ctrl+c during opening python is stuck in 
Traceback (most recent call last):
  File "C:\Users\Maxime\Documents\dev\ContactGontran\GUI\SelectorAttributWidget.py", line 72, in filterAcceptsRow
    text = self.sourceModel().stringList()[sourceRow]
KeyboardInterrupt

**Comment by gdequillacq** [comment]
We will save that table without the filter before importing.
(I'm using that excel as my database for the moment)
