### ISSUE TITLE
dans le Tableau, les roles apparaissent plsueirurs fois dans le toggle

### ISSUE THREAD

**Issue by gdequillacq** [maximeLeurent/ContactGontran#16]
quand on selectionne un role, comme "CEO" dans le haut de la fenetre 'Tableau'. plusieurs lignes 'CEO' sont possibles

**Comment by maximeLeurent** [comment]
Error during importation.
I add a sort in those list. 
During importation i remove some space at beginning and end of words.

Still a little prob for VolTrader wrote i several from. Correction in Excel First??
