### ISSUE TITLE
Retour chariot apparait comme un drole de caractere dans les comments

### ISSUE THREAD

**Issue by gdequillacq** [maximeLeurent/ContactGontran#4]
probablement

;_x000D_

**Comment by gdequillacq** [comment]
non c'est 
_x000D_

**Comment by maximeLeurent** [comment]
Correction du bug:
Remplacement du caractère _x000D_(retour chariot de excel) par \n lors de l'import
remplace de /n par os.linesep alors de l'affichage dans TextEditDelegate

commits
ef0499362cd2af8932408686889cb5b1c44a4dbb
a95c9957c073f448a78e3caf0a204ecbcb6238f5
