### ISSUE TITLE
Comment fais-tu pour bouger/redimensionner les champs dans les fenetres?

### ISSUE THREAD

**Issue by gdequillacq** [maximeLeurent/ContactGontran#8]
Exemple: ajouter "Middle Name" dans la fenetre "Tableau"

CA devrait etre dans TableauContactWidget.py ou TableauContactWindow.py

**Comment by maximeLeurent** [comment]
voir commit 879166c4d837031bc3a2de1bc18e9c3e87049799

Ajout dans la table
ListContactModel
=> self.attributToDisplay
Tu l'avais changé pour change l'ordre des colonnes

Ajout dans la liste des filtres:
FilterContactWidget => objet parent dans lineEdit et de tout les autres filtres possibles
self.addLabelLineEdit("middleName")
